# Generated by Django 3.2.7 on 2023-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phoneno',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
