# Generated by Django 3.2.7 on 2023-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
