# Generated by Django 3.2.7 on 2023-10-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bylaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bylaws',
            field=models.ManyToManyField(blank=True, to='account.ByLaw'),
        ),
    ]
