# Generated by Django 3.2.7 on 2023-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
        ('account', '0005_account_bylaws'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='generalmeetings',
            field=models.ManyToManyField(blank=True, to='meeting.Meeting'),
        ),
    ]
