# Generated by Django 3.2.7 on 2023-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0002_class_createrid'),
        ('account', '0006_account_generalmeetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slots',
            field=models.ManyToManyField(blank=True, to='eclass.Class'),
        ),
    ]
