# Generated by Django 3.2.7 on 2023-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='hourlyrate',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='hourly_rate'),
        ),
        migrations.AddField(
            model_name='account',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='languages spoken'),
        ),
        migrations.AddField(
            model_name='account',
            name='mentoringexamname',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='mentor_exam name'),
        ),
        migrations.AddField(
            model_name='account',
            name='mentoringtag',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='mentor_exam name'),
        ),
        migrations.AddField(
            model_name='account',
            name='nooflessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='noofstars',
            field=models.CharField(blank=True, default='4.2', max_length=250, verbose_name='no_of_stars'),
        ),
        migrations.AddField(
            model_name='account',
            name='noofstudents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='totalratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
