# Generated by Django 3.2.7 on 2023-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20231211_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aprovedTopper',
            field=models.CharField(blank=True, default='No', max_length=250, verbose_name='approved_topper'),
        ),
    ]
