# Generated by Django 3.2.7 on 2023-12-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20231211_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilevideolink',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='profile_video_link'),
        ),
    ]
