# Generated by Django 3.2.7 on 2023-12-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_profilevideolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mentoringexamnyear',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='mentoring_exam_n_year'),
        ),
    ]
