# Generated by Django 3.2.7 on 2023-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_mentoringexamnyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilehighlighttag',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='userprofile_highlight_tag'),
        ),
    ]
