# Generated by Django 3.2.7 on 2024-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20231228_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='EATechData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ugrlevel', models.CharField(max_length=100)),
                ('esrlevel', models.CharField(max_length=100)),
                ('flowrateline01', models.CharField(max_length=100)),
                ('pressureline01', models.CharField(max_length=100)),
                ('flowrateline02', models.CharField(max_length=100)),
                ('pressureline02', models.CharField(max_length=100)),
                ('flowrateline03', models.CharField(max_length=100)),
                ('pressureline03', models.CharField(max_length=100)),
            ],
        ),
    ]
