# Generated by Django 3.2.7 on 2023-12-04 07:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(blank=True, max_length=200, null=True)),
                ('fileaddress', models.FileField(blank=True, max_length=1055, null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('creationDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('creationTime', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
        migrations.CreateModel(
            name='LinkObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('creationDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('creationTime', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
        migrations.CreateModel(
            name='VideoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('creationDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('creationTime', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('ongoing', 'ONGOING'), ('completed', 'COMPLETED'), ('postponed', 'POSTPONED'), ('cancelled', 'CANCELLED')], default='scheduled', max_length=10)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('meetingLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('about', models.TextField(blank=True, max_length=5000, null=True)),
                ('files', models.ManyToManyField(blank=True, related_name='course_file_objects_class', to='eclass.FileObject')),
                ('links', models.ManyToManyField(blank=True, related_name='link_objects_class', to='eclass.LinkObject')),
                ('videos', models.ManyToManyField(blank=True, related_name='video_objects_class', to='eclass.VideoObject')),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
    ]
