# Generated by Django 3.2.7 on 2023-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='createrid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
