# Generated by Django 3.2.7 on 2023-12-03 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkObjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talkfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Namenotgiven', max_length=500, null=True)),
                ('talkfile', models.FileField(blank=True, max_length=5000, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talktitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('talkdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('talktime', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('outspeaker', models.CharField(blank=True, max_length=200, null=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_talk', to=settings.AUTH_USER_MODEL)),
                ('talkfiles', models.ManyToManyField(blank=True, to='meeting.Talkfile')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('about', models.TextField(blank=True, max_length=5000, null=True)),
                ('courseId', models.IntegerField(blank=True, null=True)),
                ('serialNo', models.IntegerField(blank=True, null=True)),
                ('meetingStatus', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('ongoing', 'ONGOING'), ('cancelled', 'CANCELLED'), ('postponed', 'POSTPONED'), ('completed', 'COMPLETED')], default='scheduled', max_length=10)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('meetingLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('contributions', models.ManyToManyField(blank=True, to='meeting.Presentation')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_meeting', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
    ]
